let smbData = [
    {
        name: "Bộ áo khoác LOPO",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 9 tháng",
        price: "290.000",
        photo:"img/boy/01.jpg",
    },
    {
        name: "Bộ thu đông dài tay",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 9 tháng",
        price: "180.000",
        photo:"img/boy/02.jpg",
    },
    {
        name: "Bộ khủng long xám",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 12 tháng",
        price: "120.000",
        photo:"img/boy/03.jpg",
    },
    {
        name: "Bộ đông đen số 7",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 12 tháng",
        price: "240.000",
        photo:"img/boy/04.jpg",
    },
    {
        name: "Bộ thu đông xám",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 12 tháng",
        price: "230.000",
        photo:"img/boy/05.jpg",
    },
    {
        name: "Bodysuit áo nâu dày",
        groupStyle: "Bodysuit bộ rời",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "200.000",
        photo:"img/boy/06.jpg",
    },
    {
        name: "Bodysuit áo kẻ sọc",
        groupStyle: "Bodysuit bộ rời",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "50.000",
        photo:"img/boy/07.jpg",
    },
    {
        name: "Bộ hè Wade 3",
        groupStyle: "Set quần áo",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "110.000",
        photo:"img/boy/08.jpg",
    },
    {
        name: "Bodysuit áo rời quần",
        groupStyle: "Bodysuit bộ rời",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "270.000",
        photo:"img/boy/09.jpg",
    },
    {
        name: "Bodysuit áo xanh bò",
        groupStyle: "Bodysuit bộ rời",
        groupSize: "Từ 4 đến 6 tuổi",
        price: "150.000",
        photo:"img/boy/10.jpg",
    },
    {
        name: "Bodysuit áo rêu",
        groupStyle: "Bodysuit bộ rời",
        groupSize: "Từ 4 đến 6 tuổi",
        price: "230.000",
        photo:"img/boy/11.jpg",
    },
    {
        name: "Bộ quần áo dây đeo",
        groupStyle: "Set quần áo",
        groupSize: "Từ 4 đến 6 tuổi",
        price: "200.000",
        photo:"img/boy/12.jpg",
    },
    {
        name: "Bộ quần áo Gân đan",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 3 tháng",
        price: "300.000",
        photo:"img/boy/13.jpg",
    },
    {
        name: "Bodysuit hoạt hình",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 3 tháng",
        price: "278.000",
        photo:"img/boy/14.jpg",
    },
    {
        name: "Bodysuit khủng long",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 3 tháng",
        price: "129.000",
        photo:"img/boy/15.jpg",
    },
    {
        name: "Bodysuit ô tô",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 3 tháng",
        price: "119.000",
        photo:"img/boy/15.jpg",
    },
    {
        name: "Áo bơi sọc dưa hấu",
        groupStyle: "Đồ bơi",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "210.000",
        photo:"img/girl/17.jpg",
    },
    {
        name: "Bodysuit bộ vàng",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 9 tháng",
        price: "170.000",
        photo:"img/girl/02.jpg",
    },
    {
        name: "Váy thuỷ thủ trắng",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "150.000",
        photo:"img/girl/03.jpg",
    },
    {
        name: "Váy hồng nơ xinh",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "170.000",
        photo:"img/girl/04.jpg",
    },
    {
        name: "Váy chấm bi nơ xanh",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "245.000",
        photo:"img/girl/05.jpg",
    },
    {
        name: "Váy chấm bi trắng",
        groupStyle: "Váy, đầm",
        groupSize: "Trẻ 12 tháng",
        price: "210.000",
        photo:"img/girl/06.jpg",
    },
    {
        name: "Váy chấm bi xanh",
        groupStyle: "Váy, đầm",
        groupSize: "Trẻ 12 tháng",
        price: "110.000",
        photo:"img/girl/07.jpg",
    },
    {
        name: "Váy hồng kẻ sọc",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "160.000",
        photo:"img/girl/08.jpg",
    },
    {
        name: "Váy nơ xám nâu",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "330.000",
        photo:"img/girl/09.jpg",
    },
    {
        name: "Váy đai xám nâu",
        groupStyle: "Váy, đầm",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "350.000",
        photo:"img/girl/10.jpg",
    },
    {
        name: "Bodysuit áo xanh",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 12 tháng",
        price: "150.000",
        photo:"img/girl/11.jpg",
    },
    {
        name: "Bodysuit bộ liền cam",
        groupStyle: "Bodysuit bộ liền",
        groupSize: "Trẻ 12 tháng",
        price: "130.000",
        photo:"img/girl/12.jpg",
    },
    {
        name: "Bộ động vật dễ thương",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 12 tháng",
        price: "249.000",
        photo:"img/girl/13.jpg",
    },
    {
        name: "Bộ hoạt hình hồng xinh",
        groupStyle: "Set quần áo",
        groupSize: "Trẻ 12 tháng",
        price: "219.000",
        photo:"img/girl/14.jpg",
    },
    {
        name: "Đầm nơ kẻ sọc",
        groupStyle: "Đầm, váy",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "249.000",
        photo:"img/girl/15.jpg",
    },
    {
        name: "Áo sơ mi viền lá",
        groupStyle: "Áo",
        groupSize: "Từ 2 đến 4 tuổi",
        price: "109.000",
        photo:"img/girl/16.jpg",
    }
]

